name: Publish NeoLoad Report

on:
  workflow_dispatch:
    inputs:
      workspace_id:
        description: 'NeoLoad Workspace ID'
        required: true
        type: string
      result_id:
        description: 'NeoLoad Result ID'
        required: true
        type: string
      test_name:
        description: 'Name of the test'
        required: true
        type: string
      environment:
        description: 'Test environment (e.g., DEV, QA, PROD)'
        required: true
        type: string
      confluence_space_key:
        description: 'Confluence Space Key'
        required: true
        type: string
      ancestor_page_id:
        description: 'Parent Confluence Page ID'
        required: true
        type: string
      page_title:
        description: 'Title for the new Confluence page'
        required: true
        type: string

jobs:
  publish-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run NeoLoad Report Publisher
      env:
        NEOLOAD_API_TOKEN: ${{ secrets.NEOLOAD_API_TOKEN }}
        CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        WORKSPACE_ID: ${{ github.event.inputs.workspace_id }}
        RESULT_ID: ${{ github.event.inputs.result_id }}
        TEST_NAME: ${{ github.event.inputs.test_name }}
        ENVIRONMENT: ${{ github.event.inputs.environment }}
        CONFLUENCE_SPACE_KEY: ${{ github.event.inputs.confluence_space_key }}
        ANCESTOR_PAGE_ID: ${{ github.event.inputs.ancestor_page_id }}
        PAGE_TITLE: ${{ github.event.inputs.page_title }}
      run: python publish_neoload_report.py 